name: "ðŸš€ Terraform AWS CI/CD"


on:
  push:
    paths:
      - '**/*.tf'
      - 'index.html'
  repository_dispatch:
    types: [web-form-trigger]

jobs:
  terraform:
    name: "ðŸŒ Provision AWS avec Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: ðŸ“¥ Checkout du code
        uses: actions/checkout@v3

      - name: ðŸ› ï¸ Installation de Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: âš¡ Initialisation Terraform
        run: |
          echo "\033[1;34m==> Initialisation...\033[0m"
          terraform init

      - name: ðŸ” Plan Terraform
        run: |
          echo "\033[1;33m==> Planification...\033[0m"
          terraform plan

      - name: ðŸš€ Application Terraform
        run: |
          echo "\033[1;32m==> Application...\033[0m"
          terraform apply -auto-approve
